spring.application.name=yuukalikejava

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/yuukalikejava?useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=sosd_user
spring.datasource.password=sakiprime233
server.port=8520
mybatis-plus.configuration.map-underscore-to-camel-case=true